### ISSUE TITLE
need dataset

### ISSUE THREAD

**Issue by lrybbs** [zhaozhen2333/iFLYTEK2021#1]
Nice work!
However,  I can not find the dataset to the work on Internet, could you please send me the dataset?
my email address is lry199801@163.com.
thanks a lot!

**Comment by zhaozhen2333** [comment]
Thanks for following my work, the link to the dataset has been updated. You can also extract directly from the link below.
链接：https://pan.baidu.com/s/1_yFbJ6nX1ovOK0_9BZ5Lrg?pwd=1234&nbsp;提取码：1234.
All images and their associated annotations in the dataset can be used for academic purposes only, but any commercial use is prohibited.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaozhen2333/iFLYTEK2021"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月23日(星期三) 上午10:40
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaozhen2333/iFLYTEK2021] need dataset (Issue #1)





 
Nice work!
 However,  I can not find the dataset to the work on Internet, could you please send me the dataset?
 my email address is ***@***.***
 thanks a lot!
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lrybbs** [comment]
I have received the dataset
Thanks again!

**Comment by wisdom-pan** [comment]
Nice work!
However, I can not find the dataset to the work on Internet, could you please send me the dataset?
my email address is 1789244288@qq.com
thanks a lot!
