### ISSUE TITLE
Sharing Data From Alternative Cloud Platforms (Google Drive, One Drive, ...)

### ISSUE THREAD

**Issue by kcsumesh** [zhaozhen2333/iFLYTEK2021#12]
Hi, I am unable to access the data from the link shared (). Will it be possible to share the data from alternative cloud platforms (Google Drive, One Drive, ...).

Thanks in advance.

**Comment by zhaozhen2333** [comment]
One Drive: https://1drv.ms/f/s!AntJTMkziB1Aa0c0xrrjMtuljA8?e=WsPKsL

**Comment by kcsumesh** [comment]
Thanks for sharing the dataset.

The quality of the satellite images does not look great. It is blurry and the labels does not align with the image.

Is this the same data used in the challenge?

![image](https://github.com/user-attachments/assets/ce6c48c7-2f69-4792-b326-c2450601211a)

**Comment by zhaozhen2333** [comment]
> Thanks for sharing the dataset.
> 
> The quality of the satellite images does not look great. It is blurry. In the case of labels, there seems to be multiple fields in some of the polygons.
> 
> Is this the same data used in the challenge?
> 
> ![image](https://private-user-images.githubusercontent.com/101300358/356915389-ce6c48c7-2f69-4792-b326-c2450601211a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjE0MTUsIm5iZiI6MTcyNTg2MTExNSwicGF0aCI6Ii8xMDEzMDAzNTgvMzU2OTE1Mzg5LWNlNmM0OGM3LTJmNjktNDc5Mi1iMzI2LWMyNDUwNjAxMjExYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNTUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzk4NmIxYzlmYjkzMzI3MzE4Y2JiZjhjNGU4OTdlNWFlZDFhYTE2ZTY5MjUyNWNkMjNhZmRlMzdjMGIyMjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JGgNWmHu0Yh6jtCqXlIIE0f4CUkf_Pabs36I5qUrGao)
> 
> ![image](https://private-user-images.githubusercontent.com/101300358/356915538-f093305e-0c62-40ed-b43b-fe05bf79ed4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4NjE0MTUsIm5iZiI6MTcyNTg2MTExNSwicGF0aCI6Ii8xMDEzMDAzNTgvMzU2OTE1NTM4LWYwOTMzMDVlLTBjNjItNDBlZC1iNDNiLWZlMDViZjc5ZWQ0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQwNTUxNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGE1OWU1ODcyN2Y2MGY4ZTBmYWYwMDNlNGYzM2UwMmRlNDVjNzQ5YTZiM2Y4Nzk4YWUwYjJlNmJmZWEyNjYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.15lGONWpQfeSxEeGwlQ5WHSxMvhcmAZ2Mn_j1L1_J54)

Yes
