### ISSUE TITLE
RuntimeError: input image is smaller than kernel (shape_check at mmdet/ops/dcn/src/deform_conv_cuda.cpp:127)

### ISSUE THREAD

**Issue by YangPanHZAU** [zhaozhen2333/iFLYTEK2021#2]
当我训练您参数文件时，环境配置几乎与您的一样，但发现在deform conv卷积操作会发生报错，以下是我的环境配置
sys.platform: linux
Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
CUDA available: True
GPU 0: NVIDIA TITAN RTX
CUDA_HOME: /usr/local/cuda-10.1
NVCC: Cuda compilation tools, release 10.1, V10.1.105
GCC: gcc (GCC) 5.3.0
PyTorch: 1.7.1
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
  - CuDNN 7.6.3
  - Magma 2.5.2
  - Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.8.2
OpenCV: 4.5.2
MMCV: 1.3.11
MMCV Compiler: GCC 7.3
MMCV CUDA Compiler: 10.1
MMDetection: 2.15.1+

**Comment by zhaozhen2333** [comment]
抱歉，忘记在readme说明了，这就补上。因为使用滑动窗口剪切原始图片，有一定几率会得到非常小的图片，需要在transform.py里面的Pad那个类将其填充。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhaozhen2333/iFLYTEK2021"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午4:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhaozhen2333/iFLYTEK2021] RuntimeError: input image is smaller than kernel (shape_check at mmdet/ops/dcn/src/deform_conv_cuda.cpp:127) (Issue #2)





 
当我训练您参数文件时，环境配置几乎与您的一样，但发现在deform conv卷积操作会发生报错，以下是我的环境配置
 sys.platform: linux
 Python: 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0]
 CUDA available: True
 GPU 0: NVIDIA TITAN RTX
 CUDA_HOME: /usr/local/cuda-10.1
 NVCC: Cuda compilation tools, release 10.1, V10.1.105
 GCC: gcc (GCC) 5.3.0
 PyTorch: 1.7.1
 PyTorch compiling details: PyTorch built with:
  
GCC 7.3
 
C++ Version: 201402
 
Intel(R) oneAPI Math Kernel Library Version 2021.2-Product Build 20210312 for Intel(R) 64 architecture applications
 
Intel(R) MKL-DNN v1.6.0 (Git Hash 5ef631a030a6f73131c77892041042805a06064f)
 
OpenMP 201511 (a.k.a. OpenMP 4.5)
 
NNPACK is enabled
 
CPU capability usage: AVX2
 
CUDA Runtime 10.1
 
NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_37,code=compute_37
 
CuDNN 7.6.3
 
Magma 2.5.2
 
Build settings: BLAS=MKL, BUILD_TYPE=Release, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DUSE_VULKAN_WRAPPER -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, USE_CUDA=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON,
  
TorchVision: 0.8.2
 OpenCV: 4.5.2
 MMCV: 1.3.11
 MMCV Compiler: GCC 7.3
 MMCV CUDA Compiler: 10.1
 MMDetection: 2.15.1+
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by YangPanHZAU** [comment]
我需要修改transform.py 里面pad类哪个参数？

**Comment by cyq123-git** [comment]
您好，应该是 transforms.py 里的pad类，您的readme里边写错了，写成 transformer.py

**Comment by BigBigOranges** [comment]
修改了transforms.py的代码，还是会报这个错。

**Comment by Kk875** [comment]
> 修改了transforms.py的代码，还是会报这个错。

请问transforms.py 在哪个文件里

**Comment by Kk875** [comment]
> 修改了transforms.py的代码，还是会报这个错。

请问解决了吗
