### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by 1701000429** [zhaozhen2333/iFLYTEK2021#5]
你好，看到您的论文中分享测试数据是15+18张测试集，16张训练集。

百度网盘的分享中测试集只有15张，另外18张可以分享一下吗。谢谢

**Comment by zhaozhen2333** [comment]
> 

The final test set is confidential

**Comment by Kk875** [comment]
> > 
> 
> The final test set is confidential
您好，请问模型推理输出各个地区的shp，为什么在Arc GIS pro 中无法显示？
