### ISSUE TITLE
训练时存在的问题

### ISSUE THREAD

**Issue by LCNLJQ** [zhaozhen2333/iFLYTEK2021#9]
你好，我单GPU运行：`source out_shp/train/run_train.sh 1`命令时，报了这个错 `NCCL error in: /opt/conda/conda-bld/pytorch_1607370156314/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8`，请问怎么解决?
我在尝试运行`source out_shp/train/run_train.sh 0`时，程序正常运行，没有报错，但是在`./out_shp/train/512-512`目录下没有生成pth格式的权重文件，请问这应该如何解决?

**Comment by zhaozhen2333** [comment]
第一个应该是环境问题，没有设置完全。
第二个，既然正常运行了，应该train已经启动了，是不是第一个epoch还没训练完成，稍等一下
